spring.application.name=springboot
server.port=8080
spring.main.log-startup-info=true
spring.banner.location=banner.txt
spring.banner.charset=utf-8
spring.application.admin.enabled=true
debug=false
logging.file.name=logs/app.log
logging.console.enabled=true
logging.structured.format.console=logstash
logging.structured.format.file=logstash
logging.logback.rollingpolicy.file-name-pattern=logs/app.log
logging.logback.rollingpolicy.clean-history-on-start=false
logging.logback.rollingpolicy.max-file-size=102400000
#logging.logback.rollingpolicy.total-size-cap=1024000
logging.logback.rollingpolicy.max-history=7
